#!/bin/bash

if [ ! -d $HOME/.apicultor ]
then
	echo "No se han creado ni el directorio ni los archivos necesarios";
	mkdir $HOME/.apicultor;
	touch $HOME/.apicultor/hashesNuevos.csv $HOME/.apicultor/hashesAntiguos.csv $HOME/.apicultor/directoriosNuevos.csv $HOME/.apicultor/directoriosAntiguo.csv $HOME/.apicultor/diffHashes.csv $HOME/.apicultor/diffDirectorios.csv
elif [ -z "$(ls -A $HOME/.apicultor)"]
then
	echo "Existe el directorio, no los archivos"
	touch $HOME/.apicultor/hashesNuevos.csv $HOME/.apicultor/hashesAntiguos.csv $HOME/.apicultor/directoriosNuevos.csv $HOME/.apicultor/directoriosAntiguo.csv $HOME/.apicultor/diffHashes.csv $HOME/.apicultor/diffDirectorios.csv
else
	echo "todo en orden"
fi
